Makefile, README.md
=> feat: Makefile

frontend/package.json, frontend/tsconfig.json, frontend/typings/gltf.d.ts, frontend/yarn.lock
- Three.jsに必要な物をインストールしました
- ARに必要な物は未インストールです
=> Three.jsに必要な物をインストール

api/package.json, api/src/app.module.ts, api/src/schema.gql, api/src/users/users.resolver.ts, api/yarn.lock, frontend/.eslintrc.json, frontend/.prettierrc.json, frontend/package.json, frontend/src/ApolloClient.ts, frontend/src/App.tsx, frontend/src/env/dotEnv.ts, frontend/src/pages/auth/SignIn.tsx, frontend/src/pages/auth/SignUp.tsx, frontend/yarn.lock
**変更内容**
- webSoket通信を可能に変更
- フロントでsubscriptionを受け取れるように変更
=> feat:WS通信を可能にしsubscriiptionを動作するように変更

api/src/main.ts
=> feat: cors measures

api/src/allocations/allocation.ts, api/src/chats/chat.ts, api/src/game-logs/game-log.ts, api/src/groups/group.ts, api/src/interests/interest.ts, api/src/invitations/invitation.ts, api/src/list-sorts/list-sort.ts, api/src/lists/list.ts, api/src/monsters/monster.ts, api/src/projects/project.ts, api/src/schema.gql, api/src/species/specie.ts, api/src/tasks/task.ts, api/src/users/user.ts, api/src/users/users.service.ts
- allocationテーブルにエラーがあったので修正
- エラー修正
- `allocation.ts`ファイル
- #33 で見つけられなかったエラー
=> fix: allocation table task field

frontend/src/pages/projectList/projectDetail/ProjectDetail.tsx, frontend/src/pages/projectList/projectDetail/getUser.gql, frontend/src/pages/projectList/projectList.gql
- 自分のステータスを表示
- 左側のみ横スクロールする
- 今後タスクリストが追加された場合のために
- `ProjectDetail.tsx`
- #36 ← このPRにコンフリクトしやす
=> feat: 自分のステータス表示、左側だけ横スクロール

package.json
=> delete: my mail address

.husky/post-merge, package.json
- git pullしたタイミングでscriptを走らせる(多分!)
- 楽にしたい
=> feat: pull run script

Makefile, README.md
- front側もdockerで動かすためMakefileを修正
- 楽に開発したい
- `Makefile`
=> fix: makefile

frontend/src/components/ui/loading/Loading.tsx, frontend/src/context/AuthProvider.tsx
=> feat: loading

frontend/src/consts/dropType.ts, frontend/src/pages/projectList/projectDetail/ProjectDetail.tsx, frontend/src/types/list.ts
- constファイルにENUMを移動
- 読みやすいコードにすべく
`dropType.ts`
=> fix: list drop type move const file

frontend/src/hooks/useWatchInnerAspect.ts, frontend/src/pages/auth/SignUp.tsx
雑にレビューして見逃してた部分
オライリーの本にサイズ取るならこうしろって書いてあったから修正
=> fix: useWatchInnerAspect

frontend/src/components/models/task/TaskCard.tsx, frontend/src/pages/projectList/projectDetail/ProjectDetail.tsx
=> fix: Fixed a bug when Draggable is inserted into a card.

frontend/src/components/models/employee/EmployeePopover.tsx, frontend/src/components/models/task/TaskColumn.tsx, frontend/src/consts/defaultImages.ts, frontend/src/styles/globalStyle.ts
=> fix: file path

frontend/src/components/models/project/ProjectDrawer.tsx, frontend/src/components/models/task/TaskColumn.tsx, frontend/src/components/ui/avatar/ManyUserAvatar.tsx, frontend/src/components/ui/avatar/UserAvatarIcon.tsx, frontend/src/components/ui/avatar/UserCount.tsx, frontend/src/consts/avatarStyle.ts, frontend/src/consts/dropType.ts, frontend/src/consts/gqlErrorMessage.ts, frontend/src/pages/invitation/index.tsx, frontend/src/pages/projectList/projectDetail/ProjectDetail.tsx, frontend/src/styles/theme.ts
=> fix: consts type name

api/src/schema.gql, api/src/tasks/task.ts, api/src/tasks/tasks.service.ts
taskテーブルにあるend_dateをstringに変更
end_dateがない場合は空文字を送る
=> fix: task end_date nullable

api/src/allocations/allocations.module.ts, api/src/allocations/allocations.resolver.spec.ts, api/src/allocations/allocations.resolver.ts, api/src/allocations/allocations.service.spec.ts, api/src/allocations/allocations.service.ts, api/src/allocations/dto/newAllocation.input.ts, api/src/schema.gql
mutaiton create allocation の追加
```
mutation CreateAllocation {
createAllocation(newAllocation:{
task_id: String!
user_id: String!
}) {
id
}
}
```
これで作成できる
=> feat: mutation create allocation

frontend/src/components/ui/popup/SearchTaskPopup.tsx
タスク検索で期待した検索結果が返ってこなかったので修正
Trello #152
Closes #152
検索に不具合があったため
`SearchTaskPopup.tsx`
=> fix: 正常にタスク検索ができるよう修正

api/src/game-logs/dto/newGameLog.input.ts, api/src/game-logs/game-logs.module.ts, api/src/game-logs/game-logs.resolver.spec.ts, api/src/game-logs/game-logs.resolver.ts, api/src/game-logs/game-logs.service.spec.ts, api/src/game-logs/game-logs.service.ts, api/src/lists/dto/newList.input.ts, api/src/lists/lists.module.ts, api/src/lists/lists.service.ts, api/src/projects/dto/endProject.input.ts, api/src/projects/projects.module.ts, api/src/projects/projects.resolver.ts, api/src/projects/projects.service.ts, api/src/schema.gql, api/src/tasks/dto/newTask.input.ts, api/src/tasks/dto/updateTaskSort.input.ts, api/src/tasks/tasks.module.ts, api/src/tasks/tasks.service.ts, api/src/users/users.module.ts, api/src/users/users.resolver.ts, api/src/users/users.service.ts, frontend/src/components/models/project/ProjectGameLog.tsx, frontend/src/components/models/project/ProjectMonster.tsx, frontend/src/components/models/project/ProjectRight.tsx, frontend/src/consts/gameLog.ts, frontend/src/hooks/useTaskCreateForm.ts, frontend/src/pages/projectList/projectDetail/ProjectDetail.tsx, frontend/src/pages/projectList/projectDetail/projectDetail.gql
ログのスタイリングをした
mutationを追加、ログがテーブルに追加されるようにした
モンスターの総HP計算、残りHPの計算を実装
Trello #149
Closes #149
すべて
まだ、しっかりログの色が決まってないところ
=> feat: ログ周りのスタイルング、mutation & モンスターのHP処理

frontend/src/pages/projectDetail/ProjectDetail.tsx
タスクを完了のリストに移動したらcompleted flagを立てる
Trello #159
Closes #159
今まで全てcompleted flagがfalseで送られていたため
=> feat: task completed flag database

api/src/allocations/allocations.resolver.ts, api/src/allocations/dto/newAllocation.input.ts, api/src/schema.gql, api/src/tasks/tasks.resolver.ts, api/src/tasks/tasks.service.ts, frontend/src/hooks/useTaskCreateForm.ts, frontend/src/pages/projectDetail/projectDetail.gql
=> add: タスク作成時にユーザーも追加できるようにした

api/src/game-logs/game-logs.service.ts, frontend/src/hooks/usePresence.ts, frontend/src/pages/projectDetail/ProjectDetail.tsx, frontend/src/routes/AppRoutes.tsx
プレゼンス機能にてオフラインになるよう修正
Trello #170
Closes #170
今までプレゼンス機能がオフラインにならなかったため
`AppRoutes.tsx`
力技なコードなため不安があります
=> fix: プレゼンス機能

frontend/src/hooks/useGameLog.ts
ログがキャッシュされていて更新がしっかりされていないので修正
Trello #185
Closes #185
ログを動け！
=> bugfix: ログがキャッシュされないように

frontend/src/components/ui/header/ProjectDetailHeader.tsx, frontend/src/components/ui/header/ProjectListHeader.tsx
ヘッダーのロゴを押したらインデックスページに戻る
Trello #187
Closes #187
戻ってくれ！て感じ
=> fix: ヘッダーのロゴを押したらインデックスページに戻る

frontend/src/pages/projectList/ProjectList.tsx
プロジェクトリストページのバックグランドイメージがしっかり表示されるように修正
Trello #189
Closes #189
表示されてくれ！的な⭐️
=> bugfix: プロジェクトリストページのバックグランドイメージがしっかり表示されるように

api/src/tasks/tasks.service.ts, frontend/src/pages/projectDetail/ProjectDetail.tsx
タスク移動してもデータベースが更新されないバグを修正
Trello #191
Closes #191
=> タスク移動できないバグを修正

api/src/projects/projects.service.ts, api/src/users/users.service.ts, frontend/src/components/models/employee/EmployeeInformation.tsx, frontend/src/components/models/employee/EmployeePopover.tsx, frontend/src/components/models/myPage/MyPageUserInfo.tsx, frontend/src/components/models/project/ProjectMyInfo.tsx, frontend/src/components/models/projectList/ProjectListProjectInfo.tsx, frontend/src/components/ui/avatar/ManyUserAvatar.tsx, frontend/src/components/ui/form/SearchMemberField.tsx, frontend/src/hooks/useTrySignUp.ts, frontend/src/pages/auth/SignUp.tsx, frontend/src/pages/auth/document.gql, frontend/src/pages/auth/signUp.gql, frontend/src/pages/mypage/MyPage.tsx, frontend/src/pages/mypage/mypage.gql, frontend/src/pages/projectDetail/ProjectDetail.tsx, frontend/src/pages/projectDetail/getUser.gql, frontend/src/pages/projectDetail/projectDetail.gql, frontend/src/pages/projectList/projectList.gql
職業テーブルの追加に伴い、エラーが大量に出たので修正
Trello #200
Closes #200
今まで通りにTAoSKを使えるように
いろんなとこ
確認不足で職業の表示にエラーが出てるページがあるかも
=> bugfix: 職業テーブルの追加に伴う修正

api/src/tasks/tasks.service.ts
タスクを完了リスト以外のリストに戻したら経験値が入ったユーザ全員の経験値を元の経験値に戻す
Trello #202
Closes #202
あなたの経験値なかったことにしてやるぜぇ⭐️
=> fix: タスクを完了リスト以外のリストに移動したらロールバックする

frontend/src/consts/firebaseError.ts, frontend/src/hooks/useTrySignIn.ts, frontend/src/hooks/useTrySignUp.ts
エラー処理を追加した(トーストを追加p
Trello #194
Closes #194
エラー画面が出ていたので
エラーを全て網羅しているかどうか
=> bugfix: auth周りのエラー処理を修正

frontend/src/consts/regex.ts, frontend/src/hooks/useSignUpForm.ts, frontend/src/pages/auth/SignUp.tsx
新規登録にて空白だけの場合はdisabledにする
Trello #157
Closes #157
空白でも送信が出来てしまっていたため
- 力技コードにした
=> fix: 新規登録にて空白だけの場合はdisabledに

frontend/src/components/ui/wrapper/ContentWrapper.tsx
heightが100vhになっていたので100%にした
Trello #265
Closes #265
=> fix: ContentWrapperによりスクロールできなくなっていた問題を修正 #265

frontend/src/components/models/user/UserAccountSettingModal.tsx, frontend/src/hooks/useChangeEmailForm.ts
=> メールアドレス変更のエラーメッセージを修正とパスワードの変更メールを送信

frontend/src/components/models/project/ProjectMyBars.tsx
=> fix: プロジェクト詳細ページのユーザのHP, MP, EXPのスタイルをある程度崩れないように

api/src/allocations/allocations.resolver.ts, api/src/allocations/allocations.service.ts, api/src/chats/chats.resolver.ts, api/src/chats/chats.service.ts, api/src/projects/projects.resolver.ts, api/src/schema.gql, api/src/tasks/models/udatedTask.model.ts, api/src/tasks/tasks.resolver.ts, api/src/tasks/tasks.service.ts, frontend/src/components/models/task/TaskEditOverviewField.tsx, frontend/src/components/models/task/TaskEditStatusPointField.tsx, frontend/src/components/models/task/TaskEditTitleField.tsx, frontend/src/hooks/subscriptions/useChatSubscription.ts, frontend/src/hooks/subscriptions/useListsByTaskSubscription.ts, frontend/src/hooks/useShowChats.ts, frontend/src/hooks/useTaskCreateForm.ts, frontend/src/hooks/useTaskEndDateEditForm.ts, frontend/src/hooks/useTaskOverviewEditForm.ts, frontend/src/hooks/useTaskStatusPointEditForm.ts, frontend/src/hooks/useTaskTitleEditForm.ts, frontend/src/pages/projectDetail/ProjectDetail.tsx, frontend/src/pages/projectDetail/projectDetail.gql
タスク周りのみ、subscriptionを実装
#180 ← ここにエラーやどう実装したらわからないことを記述してある
- タスク周り以外のsubscriptionの実装
=> feat: タスク周りのみのsubscription実装

api/src/allocations/allocations.resolver.ts, api/src/allocations/allocations.service.ts, api/src/chats/chats.resolver.ts, api/src/chats/chats.service.ts, api/src/projects/projects.resolver.ts, api/src/schema.gql, api/src/tasks/models/udatedTask.model.ts, api/src/tasks/tasks.resolver.ts, api/src/tasks/tasks.service.ts, api/src/users/users.resolver.ts, api/src/users/users.service.ts, frontend/src/components/models/task/TaskEditOverviewField.tsx, frontend/src/components/models/task/TaskEditStatusPointField.tsx, frontend/src/components/models/task/TaskEditTitleField.tsx, frontend/src/hooks/subscriptions/useChatSubscription.ts, frontend/src/hooks/subscriptions/useListsByTaskSubscription.ts, frontend/src/hooks/useGameLog.ts, frontend/src/hooks/useShowChats.ts, frontend/src/hooks/useTaskCreateForm.ts, frontend/src/hooks/useTaskEndDateEditForm.ts, frontend/src/hooks/useTaskOverviewEditForm.ts, frontend/src/hooks/useTaskStatusPointEditForm.ts, frontend/src/hooks/useTaskTitleEditForm.ts, frontend/src/pages/projectDetail/ProjectDetail.tsx, frontend/src/pages/projectDetail/projectDetail.gql
ログ周りのみのsubscriptionを実装
#277 ← ここからブランチを切ってる
#180 ← ここにエラーなどが書かれている
=> ログ周りのみのsubscriptionを実装

api/src/schema.gql, api/src/users/users.resolver.ts, api/src/users/users.service.ts, frontend/src/components/models/employee/EmployeeProjectMembers.tsx, frontend/src/hooks/subscriptions/useOnlineSubscription.ts, frontend/src/pages/projectDetail/projectDetail.gql
オンライン・オフライン周りのsubscriptionを実装
#180 ← ここにエラーなどを書いている
=> feat: オンライン・オフライン周りのsubscription

api/src/list-sorts/list-sorts.module.ts, api/src/list-sorts/list-sorts.resolver.ts, api/src/list-sorts/list-sorts.service.ts, api/src/lists/lists.resolver.ts, api/src/lists/lists.service.ts, api/src/schema.gql, api/src/tasks/tasks.service.ts, frontend/src/hooks/subscriptions/useListsByListSortSubscription.ts, frontend/src/hooks/subscriptions/useListsByListSubscription.ts, frontend/src/hooks/useInput.ts, frontend/src/hooks/useProjectDetail.ts, frontend/src/pages/projectDetail/ProjectDetail.tsx, frontend/src/pages/projectDetail/projectDetail.gql
リスト周りのsubscriptionを実装
#180 ← エラーなどはここに書いてある
=> feat: リスト周りのsubscription

frontend/src/components/models/myPage/MyPageTags.tsx, frontend/src/pages/projectList/ProjectList.tsx
=> fix: Fixed the problem of scroll bars always appearing.

api/src/schema.gql, api/src/tasks/tasks.resolver.ts, api/src/tasks/tasks.service.ts, frontend/src/hooks/subscriptions/useUserByTaskSubscription.ts, frontend/src/pages/projectDetail/ProjectDetail.tsx, frontend/src/pages/projectDetail/projectDetail.gql
プロジェク詳細ページの自分のステータス周りのsubscription
#180 ← エラーなどはここに記載されている
=> feat: プロジェク詳細ページの自分のステータス周りのsubscription

api/src/chats/chats.resolver.ts, api/src/chats/chats.service.ts, api/src/list-sorts/list-sorts.resolver.ts, api/src/list-sorts/list-sorts.service.ts, api/src/lists/lists.resolver.ts, api/src/lists/lists.service.ts, api/src/schema.gql, api/src/tasks/tasks.resolver.ts, api/src/tasks/tasks.service.ts, api/src/users/users.resolver.ts, frontend/src/hooks/subscriptions/useUserByTaskSubscription.ts, frontend/src/hooks/useDeleteTask.ts
複数人が別々のプロジェクトを開いてあるプロジェクトを更新したらもう一つのプロジェクトの内容が更新したプロジェクトの内容に変わってしまっていた
Trello #286
Closes #286
正常にsubscriptionさせるために
見逃しているsubscriptionがないか
=> bugfix: subscriptionの致命的なバグの修正

api/src/certifications/certifications.resolver.ts, api/src/certifications/certifications.service.ts, api/src/interests/interests.resolver.ts, api/src/interests/interests.service.ts, api/src/schema.gql, api/src/users/users.resolver.ts, frontend/src/hooks/useGetCurrentUserData.ts, frontend/src/pages/projectDetail/getUser.gql
マイページ周りのsubscriptionの実装
#180 ← エラーなどはここに記載している
=> feat: マイページ周りのsubscriptionの実装

api/src/schema.gql, api/src/tasks/tasks.module.ts, api/src/tasks/tasks.resolver.ts, api/src/tasks/tasks.service.ts, frontend/src/components/models/employee/EmployeeProjectMembers.tsx, frontend/src/hooks/subscriptions/useGroupByTaskSubscription.ts, frontend/src/hooks/subscriptions/useOnlineSubscription.ts, frontend/src/pages/projectDetail/projectDetail.gql
プロジェクト詳細ページのメンバー周りのsubscriptionを実装
#180 ← ここにエラーなどを記述している
=> feat: メンバー周りのsubscriptionを実装

frontend/src/components/models/employee/EmployeeProjectMembers.tsx
- `Uncaught TypeError: groupList.map is not a function`と言われてしまいタスク画面に入れない問題を修正
Trello #299 
Closes #299
=> fix: groupList.map is not a function

api/src/projects/projects.resolver.ts, api/src/projects/projects.service.ts, api/src/schema.gql, frontend/src/hooks/useGetCurrentUserData.ts, frontend/src/hooks/useProjectDetail.ts, frontend/src/pages/projectDetail/getUser.gql
プロジェクト作成周りのsubscriptionを実装
#180 ← ここにエラー周りについて記載している
=> feat: プロジェクト作成周りのsubscriptionを実装

frontend/src/hooks/subscriptions/useGroupByTaskSubscription.ts, frontend/src/hooks/subscriptions/useOnlineSubscription.ts
メンバーがプロジェクト詳細ページから抜けたりするとメンバー情報が消えるバグが発生していたので修正
Trello #302
Closes #302
=> bugfix: メンバー情報が消えてしまう問題の修正

api/src/chats/chats.module.ts, api/src/chats/chats.resolver.ts, api/src/chats/chats.service.ts, api/src/schema.gql, frontend/src/hooks/subscriptions/useListsByChatSubscription.ts, frontend/src/hooks/useProjectDetail.ts, frontend/src/pages/projectDetail/projectDetail.gql
チャットカウント周りのsubscriptionを実装
#180 ← ここにエラーなどを記載している
=> feat: チャットカウント周りのsubscriptionを実装

frontend/src/components/ui/modal/Modal.tsx, frontend/src/styles/animation/modalAnimation.ts, frontend/src/styles/theme.ts
- `styles/animation/modalAnimation.ts`を作成し、そこでアニメーション関連の一元管理を行なった
Trello #178 
Closes #178 
モーダルにアニメーションを付与する
https://user-images.githubusercontent.com/47961006/147378666-74db6277-ad72-4244-aa54-0538c80f7e9b.mov
=> add: モーダルを開いた時のアニメーションを付与

api/src/tasks/tasks.service.ts, frontend/src/components/models/projectList/ProjectListCreateModal.tsx, frontend/src/components/models/task/TaskCreateModal.tsx, frontend/src/components/models/task/TaskEditModal.tsx, frontend/src/components/ui/form/SearchMemberFieldFromProjectCreate.tsx, frontend/src/hooks/subscriptions/useListsByTaskSubscription.ts
アサインしているメンバーが他のタスクにも継承されてしまうバグの修正
Trello #323
Closes #323
力技コード
=> bugfix: アサインしているメンバーが他のタスクに継承されてしまうバグの修正

frontend/src/components/ui/form/SearchMemberField.tsx
「パーティー」の文言を統一
Trello #329
Closes #329
=> fix: 「パーティー」の文言を統一

frontend/src/components/models/project/ProjectDrawer.tsx
プロジェクト詳細ページにあるリストが少しスクロールしてしまうので修正
Trello #326
Closes #326
=> fix: リストが少しスクロールしてしまう問題を修正

frontend/src/hooks/subscriptions/useFetchSubscriptionCurrentUserDataFromProjectDetail.ts, frontend/src/hooks/subscriptions/useFetchSubscriptionCurrentUserFromMyPage.ts, frontend/src/hooks/subscriptions/useFetchSubscriptionCurrentUserFromProjectList.ts, frontend/src/hooks/subscriptions/useNotificationSubscription.ts, frontend/src/hooks/subscriptions/useUserByTaskSubscription.ts, frontend/src/hooks/useGetCurrentUserData.ts, frontend/src/pages/mypage/MyPage.tsx, frontend/src/pages/projectDetail/ProjectDetail.tsx, frontend/src/pages/projectList/ProjectList.tsx
currentUser関連のsubscriptionを分割
Trello #312
Closes #312
=> fix: currentUser関連のsubscriptionの分割

api/src/schema.gql, api/src/tasks/tasks.resolver.ts, frontend/src/hooks/useProjectDetailDragEnd.ts, frontend/src/pages/projectDetail/projectDetail.gql
他のリスト → 完了リスト / 完了リスト → 他のリストに移動したらアサイン用のInputが変化しないバグがあったので修正
Trello #320
Closes #320
すごい力技のコード
=> bugfix: 他のリスト → 完了リスト / 完了リスト → 他のリストに移動したらアサイン用のInputができるように

api/src/lists/lists.service.ts
リストを作成してから削除すると二つ消えるバグの修正
Trello #328
Closes #328
=> bugfix: リストを作成してから削除すると二つ消えるバグの修正

api/src/tasks/tasks.resolver.ts, api/src/tasks/tasks.service.ts
完了リストにあるタスクを削除した場合の経験値などを再計算するよう修正
Trello #344
Closes #344
=> fix: 完了リストにあるタスクを削除した場合の経験値などを再計算

frontend/src/hooks/useGameLog.ts
=> fix: ゲームログを二重に取得している #355

frontend/src/components/models/projectList/ProjectListItem.tsx
プロジェクト一覧のアイテムのアニメーションを速くした
Trello #361
Closes #361
=> fix: プロジェクト一覧のアニメーションを速く

frontend/.yarnrc, frontend/public/index.html, frontend/src/components/ui/loading/Loading.tsx, frontend/src/hooks/useCompleteAnimation.ts
JSON.parse()の || 'null' 気持ち悪いけどないとactions→azureデプロイ時に失敗しちゃうので
https://qiita.com/qwq00/items/9cd8b8e095bea0633a88
Trello # 
Closes #
=> azureデプロイに必要な部分を追加

api/src/tasks/tasks.service.ts
AR側とのsocket通信が上手くいってなかったので修正
Trello #371
Closes #371
=> fix: socket通信の修正

api/src/brain-waves/brain-waves.controller.ts, api/src/tasks/tasks.service.ts, api/src/users/users.service.ts
ARに必要なcontrollerを追加
Trello #373
Closes #373
=> feat: ARに必要なcontrollerを追加
