team-essence/TAoSK

frontend/package.json
frontend/src/App.tsx
frontend/src/pages/auth/SignIn.tsx
frontend/src/pages/auth/SignUp.tsx
frontend/src/pages/home/Dashboard.tsx
frontend/yarn.lock

react-routerのメジャーバージョンがv6になったのでライブラリのアップデートと、書き方も少し変わったので修正

chore: Update React-router to v6

---

frontend/src/pages/projectList/projectList.gql

- プロジェクトの作成時、モンスターHPの初期値を0に
- 今後、モンスターHPが変動するため

fix: プロジェクト作成時、モンスターHPを0に

---

api/src/allocations/allocation.ts
api/src/groups/group.ts
api/src/groups/groups.module.ts
api/src/groups/groups.resolver.spec.ts
api/src/groups/groups.resolver.ts
api/src/groups/groups.service.spec.ts
api/src/groups/groups.service.ts
api/src/projects/project.ts
api/src/projects/projects.resolver.ts
api/src/projects/projects.service.ts
api/src/schema.gql
api/src/users/users.resolver.ts
api/src/users/users.service.ts
frontend/src/pages/auth/signUp.gql
frontend/src/pages/projectList/projectDetail/ProjectDetail.tsx
frontend/src/pages/projectList/projectDetail/projectDetail.gql

- プロジェクトページにてメンバーをリスト表示
- オンライン・オフラインで分ける
- ページに来たタイミングでオンライン
- ページを離れたタイミングでオフライン
- 今後、正式なデザインが出来上がった時のためにデータ取得出来ている状態にするため
- オンライン・オフラインの切り替えるコード
- 外部キーを修正したprojectテーブルとgroupテーブル
- まだ、ソケット通信は実装していないが外部結合でデータを取ってきているのでオンライン・オフラインの状態を更新して取得できるかどうか

feat: メンバーリストの追加

---

frontend/src/pages/projectList/projectList.gql

- `projectList.gql`にてHPとMPが二つあったので一つに

fix: projectList.gqlのHPとMPを一つに

---

.dockerignore
.gitignore
docker-compose.yml
frontend/Dockerfile

- TAOSKフォルダー配下でdocker起動でapiとfrontとdbが一斉に起動するように変更
- 開発環境の統一
- なし
- フロントコンテナ内でyarn install など新規のパケージのインストールが遅い気がする。docker内で通信速度制限みたいなのが掛かってる??? 調査はしてないので体感
初回
```
cd TAOSK 
docker-compose up --build 
(前回のボリュームが邪魔して入らない場合はコンテナの削除もしくは下記で不要ボリュームが消される
docker volume rm `docker volume ls -q -f dangling=true`) 
```
2回目以降
```
cd TAOSK 
docker-compose up 
(立ち上がらなければ docker-compose down)
```
フロントのshellにはvscodeのdockerから`taosk-fron-server`を右クリックでshellに入るのが楽そう

feat:フロントのdocker起動を追加

---

frontend/src/components/ui/form/ImageInputField.tsx
frontend/src/components/ui/form/InputField.tsx
frontend/src/components/ui/form/ItemInputField.tsx
frontend/src/components/ui/form/SelectField.tsx
frontend/src/components/ui/header/AuthHeader.tsx
frontend/src/consts/certificationsAndInterests.ts
frontend/src/hooks/useTextItems.ts
frontend/src/pages/auth/SignIn.tsx
frontend/src/pages/auth/SignUp.tsx
frontend/src/pages/projectList/projectDetail/ProjectDetail.tsx
frontend/src/types/fieldProps.ts

主に資格/興味部分の要件の追加に合わせて微修正を行なった
- 画像のところにカーソルを合わせたらpointerになるようにした
- 興味/資格
- 追加時に空白を弾く
- 興味/資格の横に n / 20 の表示をする
- 興味/資格の上限を20個までとする
- 興味/資格の文字数制限を50文字までとする
- imgにalt属性をつける
- styles-componentで余分にattr使っている部分の可読性が低かったので削除してpropsで渡すようにした
- marginBottomを全て削除した
- 興味/資格の最大文字数、最大数に関しては、constsフォルダに格納した
Trello #74 
Closes #74 
- 資格/興味部分を微修正してUXを上げる
- 細かなリファクタを行い可読性を上げる
- itemsの管理部分は `useTextItems.ts` というフックに分けた
- 見た目以外のロジック全部切り出したいなと思ったため
- メンバー追加時など、他に使える場面があるかもしれないため
- この切り出し方は適切かどうか
新規登録の横スクロールが若干できてしまう問題に関して、自分の環境では再現できなかったので別issueとする
Chromeで検証から画面サイズを変えたり、大きめのディスプレイで表示したりMacbook pro 13inchi上で表示したりと色々試したが、再現できなかった

fix: 新規登録画面の微修正 #74

---

frontend/src/components/ui/button/SimpleRoundedButton.tsx
frontend/src/components/ui/form/ImageInputField.tsx
frontend/src/components/ui/form/InputField.tsx
frontend/src/components/ui/form/InputItem.tsx
frontend/src/components/ui/form/ItemInputField.tsx
frontend/src/components/ui/form/PasswordField.tsx
frontend/src/components/ui/form/SelectField.tsx
frontend/src/components/ui/header/AuthHeader.tsx
frontend/src/pages/auth/SignIn.tsx
frontend/src/pages/auth/SignUp.tsx
frontend/src/styles/theme.ts
frontend/src/utils/calculateVwBasedOnFigma.ts
frontend/src/utils/calculateVwFromStandardSize.ts

- px指定していたものを**全てvwにした**
- `calculateVwBasedOnFigma`というメソッドを作成し、Figmaで設定されているpxを入力するとvwに変換して出力してくれるようにした
- この関数を至るところで使い強制的にレスポンシブにした
- border や box-shadows に関しては固定値でいいと思ったのでvwにはしていない
Trello #65 
Closes #65 
- ディスプレイでもPC上でもFigmaの画面設計通りのデザインになるようにする
- `theme.ts` の font-size もvwにしている
- 今回はPC以外に対応する予定はないので、font-sizeがvwでも問題ないと判断した
- #67

PC上ではカンプ通りのデザインで表示されるようにした

---

frontend/src/App.tsx
frontend/src/components/ui/form/ImageInputField.tsx
frontend/src/hooks/useDataUrlToBlob.ts
frontend/src/index.tsx
frontend/src/pages/auth/SignUp.tsx
frontend/src/routes/AppRoutes.tsx
frontend/src/routes/Protected.tsx

- ドット絵化を無しにした（hookで切り分けたから戻すときは簡単）
- components/ImageInputField の object-fitとpaddingを修正
Trello #89 
Closes #89

プロフィール画像のドット化を無効にする

---

Makefile
frontend/public/svg/tag-triangle-small_background.svg
frontend/src/components/models/myPage/MyPageTags.tsx
frontend/src/components/ui/tag/Tag.tsx

タグが他の画面では小さいので小さいサイズのスタイルを適用
```
TAG_TYPE,NORMAL ← 普通のサイズ
TAG_TYPE.SMALL ← 小さいサイズ
```
スタイルを分けるため
バツボタンのデザインが見つけられず、現状だとバツボタンが出現したらタグが少し大きくなる

feat: 小さいサイズとタグスタイルを追加

---

frontend/src/hooks/useTaskCreateForm.ts
frontend/src/pages/projectList/projectDetail/ProjectDetail.tsx

タスクの作成、更新時にcompleted_flgがないのでエラーが起きていたので修正した

fix: タスクの作成、更新時のデータにcompleted_flgを追加

---

api/src/tasks/tasks.service.ts
frontend/src/components/models/task/TaskColumn.tsx
frontend/src/components/models/task/TaskCreateModal.tsx
frontend/src/hooks/useTaskCreateForm.ts

タスク追加時のlist_idが`1`で固定されてたのでlist_idがプロジェクトごとに追加できるようにした
Trello #150
Closes #150
現状だと、全てのプロジェクトで扱えなかったため
編集したフォイル

fix: タスク追加時のタスクIDが固定だったので修正

---

api/src/game-logs/game-logs.resolver.ts
api/src/game-logs/game-logs.service.ts
api/src/projects/projects.service.ts
api/src/schema.gql
frontend/src/components/models/project/ProjectRight.tsx
frontend/src/hooks/useGameLog.ts
frontend/src/pages/projectDetail/ProjectDetail.tsx
frontend/src/pages/projectDetail/projectDetail.gql

ゲームログを今まで全て取ってきたのを最新25件取得するようにする
Trello #162
Closes #162
今後ログの数が増えるため

fix: ゲームログを最新25件取得してくる

---

Makefile
README.md
api/.gitignore
api/package.json
api/prisma/lib/occupation.ts
api/prisma/schema.prisma
api/prisma/seed.ts
api/src/occupations/occupation.ts
api/src/occupations/occupations.module.ts
api/src/occupations/occupations.resolver.spec.ts
api/src/occupations/occupations.resolver.ts
api/src/occupations/occupations.service.spec.ts
api/src/occupations/occupations.service.ts
api/src/schema.gql
api/src/users/user.ts
api/src/users/users.module.ts
api/yarn.lock

職業テーブルを追加
Trello #197
Closes #197
職業をデータベースから取得する
- 現状, `generate-gql`ができない
- gqlファイル, フロントを大幅に修正しないといけない

feat: 職業テーブルの追加

---

Makefile
README.md
api/prisma/lib/monster.ts
api/prisma/schema.prisma
api/prisma/seed.ts

モンスターのデータを流し込むseedを追加
初期起動時、モンスターデータを追加し忘れる場面が多発してるため

feat: モンスターのデータを流し込むseedを追加

---

frontend/src/components/ui/form/ItemInputField.tsx
frontend/src/consts/certificationsAndInterests.ts
frontend/src/hooks/useTextItems.ts
frontend/src/pages/auth/SignUp.tsx

新規登録の資格と興味あることを17文字以内に制限する
Trello #143
Closes #143
文字が多すぎるとタグの背景画像がガタガタにあるため
ガタガタするぜぇ！

fix: 資格と興味あることを17文字以内しか入力させないように

---

api/src/tasks/tasks.service.ts
frontend/src/pages/projectDetail/ProjectDetail.tsx

モンスターの総HPをフロント側で計算する
Trello #217
Closes #217
バックで総HPを計算するのは大変なんで

bugfix: モンスターの総HPをフロント側で計算する

---

frontend/src/components/ui/form/ItemInputField.tsx

タグのスタイルを新しいスタイルに変更
Trello #175
Closes #175
Figmaに新しいタグのスタイルが新しいのに変わっていたんでコード上も変更
`InputItem.tsx`を削除して良いものか

fix: タグのスタイルを新しいスタイルに変更

---

frontend/src/components/models/task/TaskComment.tsx
frontend/src/components/models/task/TaskCommentArea.tsx
frontend/src/components/models/task/TaskEditModal.tsx
frontend/src/components/models/task/TaskEditOverviewField.tsx
frontend/src/components/ui/avatar/UserAvatarIcon.tsx
frontend/src/components/ui/popup/HoverTriggerPopover.tsx
frontend/src/hooks/useModalInterlockingScroll.ts

- ユーザーのポップオーバーがモーダルからはみ出る時に切れてしまう問題の修正
- Material UIを使用して `HoverTriggerPopover` を作成した
- 連動スクロールの完成
- 概要未入力時は「詳しい説明を追加してください」と表示
- コメントが入力されている状態で編集をすると、最初の高さが小さい問題の修正
Closes #134
タスク編集モーダルの連動スクロールを追加して完成させる
- `useModalInterlockingScroll` の中身が直感的に分かりづらいコードになってしまった
- コメントアウトを追加して努力はしたが、まだわからない部分や、説明変数を挟んだ方がいい部分があれば指摘してほしい
#198 
#214 
- 細かい修正（issue化しておく）
- リロード後に最初に開いたタスクのユーザー数、ステータスポイントが他のタスクに移っても変わらない不具合の修正
- 完了にあるタスクだけアサインを動かせないようにする 
- コメントの入力状態をキャッシュする
- 連打防止処理の追加
- アカウント設定モーダル引き継ぐ

add,fix: タスク編集モーダルの完成 (連動スクロール、ポップオーバーの不具合修正)

---

frontend/src/components/models/task/TaskComment.tsx
frontend/src/components/models/task/TaskCommentArea.tsx
frontend/src/components/models/task/TaskEditModal.tsx
frontend/src/components/ui/form/SearchMemberField.tsx
frontend/src/components/ui/popup/SearchTaskPopup.tsx
frontend/src/pages/projectDetail/ProjectDetail.tsx
frontend/src/pages/projectDetail/projectDetail.gql
frontend/src/types/task.ts

- コメントでユーザーホバー時に職業表示
- 完了にあるタスクはアサインを動かせなくする
Trello #229 #230 
Closes #229 #230 
#227
#208
#183

fix: コメントでユーザーホバー時に職業表示, 完了にあるタスクはアサインを動かせなくする

---

frontend/src/components/models/project/ProjectDrawer.tsx
frontend/src/components/models/task/TaskCard.tsx
frontend/src/components/models/task/TaskColumn.tsx
frontend/src/components/ui/loading/Loading.tsx

スクロールバー分カードが小さくなるのが原因
widthを伸ばすことで解決
Trello #237 
Closes #237

タスクカードの日付が潰れる問題を修正

---

frontend/src/components/ui/popup/SearchTaskPopup.tsx
frontend/src/components/ui/popup/TaskCardPopup.tsx

検索結果のタスクを押下したときにモーダルを表示できるようにした
Trello #240 
Closes #240

add: 検索結果のタスクを押下したときにモーダルを表示できるようにした #240

---

api/src/tasks/tasks.service.ts

タスクを完了リストに移動した時にステータスポイントがユーザに振り分けらるように(忘れてました！)
Trello #257
Closes #257
完了リストに移動した時にステータスが振られるように

fix: ユーザごとにステータスを振り分けるように

---

frontend/src/components/ui/wrapper/ContentWrapper.tsx
frontend/src/pages/projectList/ProjectList.tsx

- プロジェクト一覧画面で画面下部に黒い余白ができてしまう問題の修正
- プロジェクト数が多い時にリストの外にアイテムが飛び出してしまう問題の修正
- プロジェクトのリストアイテムの右側が見切れてしまう問題の修正
Trello #267 
Closes #267 
プロジェクト一覧のスタイリングの不具合を修正
プロジェクト一覧画面で画面下部に5pxほどの白い余白ができており、謎スクロールができてしまう
ContentWrapperが関係あるかもと思ったが全く関係なく、html以下の要素が全て100vh未満であっても発生する
解決策が全くわからなく原因も不明だったことと、大して気にならないたと判断して放置した
issueにした方がいいかなぁ？無視してもいい？？？
https://user-images.githubusercontent.com/47961006/147089279-919325b5-15c2-4ec4-b433-557ba175ce20.mov
#262

fix: プロジェクト一覧画面のスタイリングを修正

---

frontend/src/components/models/task/TaskComment.tsx
frontend/src/utils/date/date.ts

コメントしたの時間を表示
Trello #228
Closes #228
- データベースから取得した日付にタイムゾーンを適応して、日本との時間の差９時間を足してしまう
[date-fnsで「○分前」「約○時間前」「○日前」など現在時刻からのざっくりした時間経過を表示する](https://yucatio.hatenablog.com/entry/2019/12/09/084010)

fix: format distance chat message

---

frontend/src/components/models/projectList/ProjectListCreateModal.tsx
frontend/src/components/ui/form/TextAreaField.tsx

- 概要の文字数が多い時にエラーを表示
- テキストエリアを動かせないようにした
Trello #288 #290 
Closes #288 #290

fix: プロジェクト作成の概要のエラーが表示されない問題の修正

---

frontend/public/index.html
frontend/src/components/ui/modal/Modal.tsx

- モーダル内で使う画像をpreloadで取得し、初回のカクつきを若干減らした
- muiのモーダルのoverlayの透過度を下げるついでに`will-change: animation, opacity`を付与してパフォーマンスの向上を狙ったが、効果は感じられなかった
Trello #226 
Closes #226 
https://user-images.githubusercontent.com/47961006/147372208-d202f9af-0b59-4897-aefa-8e2a3b075d78.mov
https://user-images.githubusercontent.com/47961006/147372212-0b31c010-2c3a-4c9e-9009-08fdab51166a.mov
モーダルを開いた時のカクつきをなくす
- 前よりはマシになった感覚はあるものの、やはりまだカクつくことがある
- overlayのカクつきに関しては特に改善が見られなかった
- 原因もよくわからないので、デプロイで改善することを祈りたい

improve: モーダルの初回のカクつきを若干減らした

---

frontend/src/pages/invitation/index.tsx

招待URLからプロジェクトに参加、その後ページを戻ろうとしたら変な挙動をしていたので修正
Trello #315 
Closes #315

fix: 招待URLからプロジェクトに参加した後の挙動を修正

---

frontend/src/components/models/task/TaskEditModal.tsx
frontend/src/components/models/task/TaskEditStatusPointField.tsx
frontend/src/components/models/task/TaskStatusPointField.tsx
frontend/src/hooks/useTaskStatusPointEditForm.ts

完了リストにあるタスクのステータスポイントを変更できないように修正
Trello #321
Closes #321

fix: 完了リストにあるタスクのステータスポイントを変更できないように

---

api/src/tasks/tasks.service.ts

ステータスポイントの更新ができるように修正
Trello #346
Closes #346
タスク編集モーダルを開いているときに他の人がステータスポイントを更新してもモーダル上では更新されない。上手くやればステータスポイントを無限に増やせる

bugfix: ステータスポイントの更新がんできるように

---

frontend/src/hooks/useProjectCreateForm.ts
frontend/src/hooks/useSearchSameCompanyMember.ts

プロジェクト作成時にログインしているユーザーが自動アサインされないバグを修正
Trello #358 
Closes #358 
#357 も直るかと思ったが直らなかった

fix: プロジェクト作成時にログインしているユーザーが自動アサインされないバグの修正 #358

---

frontend/src/components/models/egg/Egg.tsx
frontend/src/components/models/monster/Dragon1125.tsx

azure storageからcgのモデルを取得する
Trello #366
Closes #366

fix: azure storageからモデルを取得

---

api/src/projects/projects.service.ts

プロジェクト作成時にリストが4つ作成される問題を修正
Trello #376
Closes #376

bugfix: プロジェクト作成時にリストが4つ作成されるバグの修正 #376
